GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NjYwNDQzLCJpYXQiOjE3NDc2NjAxNDMsImp0aSI6ImYxYTlmZjA0MzIwMTQ3MjU4YWU3MTMyMjc5ZDFiZjEyIiwidXNlcl9pZCI6MX0.yKuVO3706MQJ-UxKsN7zQOx8IYklUSma3HUsU0E8KcE

{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new tv"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###

