
GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzE5Njk4LCJpYXQiOjE3NDc3MTkzOTgsImp0aSI6IjBjYzA0ZjVkMjQ1ODQ0MGZiOGUzMDdiZjgzOGM3ZTU3IiwidXNlcl9pZCI6MX0.fXGQQ7PgFDNDvefimogRkbB-OXJVvhGP7wXbXQdx0iw

{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new tv"
}

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###

GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ3NzE5Njk4LCJpYXQiOjE3NDc3MTkzOTgsImp0aSI6IjBjYzA0ZjVkMjQ1ODQ0MGZiOGUzMDdiZjgzOGM3ZTU3IiwidXNlcl9pZCI6MX0.fXGQQ7PgFDNDvefimogRkbB-OXJVvhGP7wXbXQdx0iw

